name: Deploy Website

on: [push]

jobs:
  html_test:
    - name: Test Files
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        root: ./_build
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm install -g surge
      - run: surge ./_build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
