name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
    uses: dswistowski/surge-sh-action@v1
    with:
      domain: 'foo-bar.surge.sh'
      project: '.'
      login: ${{ secrets.surge_login }}
      token: ${{ secrets.surge_token }}
